### ISSUE TITLE
Incidencia al mostrar votaciones actualizadas

### ISSUE THREAD

**Issue by alvfergar** [EGC-FrontEnd-Resultados/code#2]
Si se actualiza una votación, y ésta vuelve a mostrarse, aparacen los resultados de la primera visita a la votació, no los actualizados.

**Comment by xela-alex** [comment]
La incidencia ha sido solucionada con éxito, el error radicaba en nuestra base de datos, al usarla como memoria cache, mostrando los primeros resultados consultados y no los actualizados. La solución ideal sería que "Modificación" y "Recuento" nos notificaran cuando se actualizan las votaciones, pero estos subsistemas han finalizado su etapa de desarrollo. Finalmente se ha optado por suprimir dicha memoria cache.

**Comment by xela-alex** [comment]
La incidencia ha sido solucionada con éxito, el error radicaba en nuestra base de datos, al usarla como "memoria cache", mostrando los primeros resultados consultados y no los actualizados. La solución ideal sería que "Modificación" nos notificara cuando se actualizan las votaciones, pero han finalizado su proyecto. Finalmente se ha optado por suprimir dicha "memoria cache".
